export const productList = [
    {
        "id": "cf230bd4-b4a8-4f7a-8c00-aa2f9e146000",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "64ae397d-1f10-473d-8ed8-5f32ccf7cfa8",
        "vendor_product_ref": "Cromal06iVDqb5Yv79W20",
        "cost_price": "970.0",
        "vendor_discount_percent": "3.0",
        "product_price": "1000.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 4000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This is a A.himanshu Insta Gift Voucher (GV) / Gift Card (GC) and would be accepted online at https://euphoriajewellery.in/ and can be used to purchase Gold coins Only.",
            "2.The person who has the A.himanshu GV / GC Code is deemed to be the beneficiary.",
            "3.More than one GV / GC can be used in one bill.",
            "4.This is a ONE time use GV / GC.",
            "5.No Credit note / Refund for the unused amount of the GV / GC will be given.",
            "6.A.himanshu GV / GC CANNOT be revalidated once expired.",
            "7.A.himanshu GV / GC can be clubbed with any on-going promotions on the website. However the Insta GV / GC cannot be clubbed with any other coupon/s.",
            "8.A.himanshu GV / GC cannot be redeemed on specific block out dates. A.himanshu may add or delete any date on its sole discretion.",
            "9.Any dispute related to the GV / GC should be referred to the issuing company and the decision of the issuing company shall be final.",
            "10.If an Insta Gift Voucher (GV) /Gift Card (GC) gets blocked on account of technical issue, it would get enabled in 72 hours.",
            "11.For any queries / issues related to GV / GC, raise a request at www.gvhelpdesk.com"
        ],
        "redeem_steps": [
            "Visit : <span><a target=\"_blank\" href=\"https://euphoriajewellery.in//\">https://euphoriajewellery.in//</a></span>Select your <span>product </span> & add to cart Enter : Gift Voucher Code & click on Redeem Now. -Enter coupon code manually and click on Apply GyFTR Coupon"
        ],
        "instructions": [
            "<ul>? ? ? ?? <li>Multiple Gift Vouchers can be used in 1 bill <li> Gift Vouchers can be clubbed with on-going promotions? <li>Gift Vouchers can Only be used online on https://euphoriajewellery.in/ <li class=\"no\">Gift Vouchers cannot be clubbed with other coupon(s)? </ul>"
        ],
        "created_at": "2023-04-24T06:38:51.032Z",
        "updated_at": "2023-04-24T06:38:51.032Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "64ae397d-1f10-473d-8ed8-5f32ccf7cfa8",
            "brand_id": "a402987e-c18f-4b93-939c-37b87c24d35d",
            "name": "Euphoria Jewellery Gold Coin Rs 1000",
            "description": "Euphoria Jewellery began more than a decade ago as A.Himanshu & Co. Being miners of jewels, they took the next step of manufacturing them. Visit their official website and buy gold and silver coins risk-free. Choose Euphoria Jewellery gift cards and gift vouchers for a cashless shopping experience.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1623052206676_1ohc63ujkpmbdlqs.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "a402987e-c18f-4b93-939c-37b87c24d35d",
                "name": "Euphoria Jewellery Gold Coin",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1623052206676_1ohc63ujkpmbdlqs.jpeg",
                "description": "Euphoria Jewellery began more than a decade ago as A.Himanshu & Co. Being miners of jewels, they took the next step of manufacturing them. Visit their official website and buy gold and silver coins risk-free. Choose Euphoria Jewellery gift cards and gift vouchers for a cashless shopping experience.",
                "created_at": "2023-04-24T06:28:19.396Z",
                "updated_at": "2023-05-20T06:14:02.051Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "42c302f5-fcac-4a63-a929-95137ec33c8a",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "db7a7247-bbd8-47d1-a5a3-410282aab08d",
        "vendor_product_ref": "Bata4xfRrUnT46Uv4iol",
        "cost_price": "485.0",
        "vendor_discount_percent": "3.0",
        "product_price": "500.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 2000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This is a A.himanshu Insta Gift Voucher (GV) / Gift Card (GC) and would be accepted online at https://euphoriajewellery.in/ and can be used to purchase Gold coins Only.",
            "2.The person who has the A.himanshu GV / GC Code is deemed to be the beneficiary.",
            "3.More than one GV / GC can be used in one bill.",
            "4.This is a ONE time use GV / GC.",
            "5.No Credit note / Refund for the unused amount of the GV / GC will be given.",
            "6.A.himanshu GV / GC CANNOT be revalidated once expired.",
            "7.A.himanshu GV / GC can be clubbed with any on-going promotions on the website. However the Insta GV / GC cannot be clubbed with any other coupon/s.",
            "8.A.himanshu GV / GC cannot be redeemed on specific block out dates. A.himanshu may add or delete any date on its sole discretion.",
            "9.Any dispute related to the GV / GC should be referred to the issuing company and the decision of the issuing company shall be final.",
            "10.If an Insta Gift Voucher (GV) /Gift Card (GC) gets blocked on account of technical issue, it would get enabled in 72 hours.",
            "11.For any queries / issues related to GV / GC, raise a request at www.gvhelpdesk.com"
        ],
        "redeem_steps": [
            "Visit : <span><a target=\"_blank\" href=\"https://euphoriajewellery.in//\">https://euphoriajewellery.in//</a></span>Select your <span>product </span> & add to cart Enter : Gift Voucher Code & click on Redeem Now. -Enter coupon code manually and click on Apply GyFTR Coupon"
        ],
        "instructions": [
            "<ul>? ? ? ?? <li>Multiple Gift Vouchers can be used in 1 bill <li> Gift Vouchers can be clubbed with on-going promotions? <li>Gift Vouchers can Only be used online on https://euphoriajewellery.in/ <li class=\"no\">Gift Vouchers cannot be clubbed with other coupon(s)? </ul>"
        ],
        "created_at": "2023-04-24T06:38:50.768Z",
        "updated_at": "2023-04-24T06:38:50.768Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "db7a7247-bbd8-47d1-a5a3-410282aab08d",
            "brand_id": "a402987e-c18f-4b93-939c-37b87c24d35d",
            "name": "Euphoria Jewellery Gold Coin Rs 500",
            "description": "Euphoria Jewellery began more than a decade ago as A.Himanshu & Co. Being miners of jewels, they took the next step of manufacturing them. Visit their official website and buy gold and silver coins risk-free. Choose Euphoria Jewellery gift cards and gift vouchers for a cashless shopping experience.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1623052206676_1ohc63ujkpmbdlqs.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "a402987e-c18f-4b93-939c-37b87c24d35d",
                "name": "Euphoria Jewellery Gold Coin",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1623052206676_1ohc63ujkpmbdlqs.jpeg",
                "description": "Euphoria Jewellery began more than a decade ago as A.Himanshu & Co. Being miners of jewels, they took the next step of manufacturing them. Visit their official website and buy gold and silver coins risk-free. Choose Euphoria Jewellery gift cards and gift vouchers for a cashless shopping experience.",
                "created_at": "2023-04-24T06:28:19.396Z",
                "updated_at": "2023-05-20T06:14:02.051Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "8de785d4-0e11-4597-8141-13e6fc03f7e9",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "9b126072-2712-42a2-9844-b6be66f6114f",
        "vendor_product_ref": "EuphoriaJewelleryGoldCoin8Vgd555IaRTRYDwB",
        "cost_price": "242.5",
        "vendor_discount_percent": "3.0",
        "product_price": "250.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 1000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This is a A.himanshu Insta Gift Voucher (GV) / Gift Card (GC) and would be accepted online at https://euphoriajewellery.in/ and can be used to purchase Gold coins Only.",
            "2.The person who has the A.himanshu GV / GC Code is deemed to be the beneficiary.",
            "3.More than one GV / GC can be used in one bill.",
            "4.This is a ONE time use GV / GC.",
            "5.No Credit note / Refund for the unused amount of the GV / GC will be given.",
            "6.A.himanshu GV / GC CANNOT be revalidated once expired.",
            "7.A.himanshu GV / GC can be clubbed with any on-going promotions on the website. However the Insta GV / GC cannot be clubbed with any other coupon/s.",
            "8.A.himanshu GV / GC cannot be redeemed on specific block out dates. A.himanshu may add or delete any date on its sole discretion.",
            "9.Any dispute related to the GV / GC should be referred to the issuing company and the decision of the issuing company shall be final.",
            "10.If an Insta Gift Voucher (GV) /Gift Card (GC) gets blocked on account of technical issue, it would get enabled in 72 hours.",
            "11.For any queries / issues related to GV / GC, raise a request at www.gvhelpdesk.com"
        ],
        "redeem_steps": [
            "Visit : <span><a target=\"_blank\" href=\"https://euphoriajewellery.in//\">https://euphoriajewellery.in//</a></span>Select your <span>product </span> & add to cart Enter : Gift Voucher Code & click on Redeem Now. -Enter coupon code manually and click on Apply GyFTR Coupon"
        ],
        "instructions": [
            "<ul>? ? ? ?? <li>Multiple Gift Vouchers can be used in 1 bill <li> Gift Vouchers can be clubbed with on-going promotions? <li>Gift Vouchers can Only be used online on https://euphoriajewellery.in/ <li class=\"no\">Gift Vouchers cannot be clubbed with other coupon(s)? </ul>"
        ],
        "created_at": "2023-04-24T06:38:50.417Z",
        "updated_at": "2023-04-24T06:38:50.417Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "9b126072-2712-42a2-9844-b6be66f6114f",
            "brand_id": "a402987e-c18f-4b93-939c-37b87c24d35d",
            "name": "Euphoria Jewellery Gold Coin Rs 250",
            "description": "Euphoria Jewellery began more than a decade ago as A.Himanshu & Co. Being miners of jewels, they took the next step of manufacturing them. Visit their official website and buy gold and silver coins risk-free. Choose Euphoria Jewellery gift cards and gift vouchers for a cashless shopping experience.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1623052206676_1ohc63ujkpmbdlqs.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "a402987e-c18f-4b93-939c-37b87c24d35d",
                "name": "Euphoria Jewellery Gold Coin",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1623052206676_1ohc63ujkpmbdlqs.jpeg",
                "description": "Euphoria Jewellery began more than a decade ago as A.Himanshu & Co. Being miners of jewels, they took the next step of manufacturing them. Visit their official website and buy gold and silver coins risk-free. Choose Euphoria Jewellery gift cards and gift vouchers for a cashless shopping experience.",
                "created_at": "2023-04-24T06:28:19.396Z",
                "updated_at": "2023-05-20T06:14:02.051Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "897af6b2-63b4-41a9-99d7-cea4d03df766",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "6e8cd230-58fd-4a10-a88c-9ee5397aa313",
        "vendor_product_ref": "BenettonRwJ6cqVWqPPMLlBH",
        "cost_price": "4750.0",
        "vendor_discount_percent": "5.0",
        "product_price": "5000.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 20000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This Gift Voucher is issued by Reliance Retail Limited (Reliance).",
            "2.This Gift Voucher is redeemable, and it is valid only for a minimum period of 6 months from the date of receipt.",
            "3.Gift Voucher can be redeemed at Reliance SMART, Reliance Smart Point, Reliance Digital, Reliance Trends, Reliance Jewels and My Jio Stores in India.",
            "4.Gift Voucher can’t be exchanged for cash.",
            "5.This Gift Voucher is not valid on purchase of Gold/Silver Coins.",
            "6.This Gift Voucher can be redeemed only once. Any unused amount will lapse.",
            "7.No extension of the Validity period nor refund of the value of Gift Voucher in case of failure to use the Gift Voucher on or before the validity period.",
            "8.Reliance shall not be responsible for loss or misuse of Gift Voucher and no duplicate or compensation in lieu of the Gift Voucher shall be given by Reliance.",
            "9.Reliance overall liability will not exceed the value of the Gift Voucher.",
            "10.Bearer of the Gift Voucher shall be deemed to have read, understood and accepted these terms and conditions.",
            "11.Bearer of the code of Gift Voucher is deemed to be the beneficiary of this Gift Voucher. Any redemption by the bearer of Gift Voucher shall be considered as a valid discharge of liabilities by Reliance.",
            "12.Reliance shall not be liable under any circumstances towards any loss or damage or expenses or cost or any third-party liability, whether directly or indirectly arising out of or in relation to use of Gift Voucher and redemption thereunder by the bearer.",
            "13.Reliance reserves its right to modify/amend the terms and conditions of the Gift Voucher at any time without prior notice and such modifications shall be binding on the user/bearer of the Gift Voucher.",
            "14.Any dispute with regard to Product liability, guarantee, warranty and quality of the Products to be purchased under redemption of the Gift Voucher shall be addressed to the respective Manufacturer/ Brand Owner and Reliance shall not be held responsible/liable for the same. The guarantee and warranty of the Products shall be transferred, as received from the respective Manufacturer/Distributor.",
            "15.In case of any issue faced by the Gift Voucher bearer, the Gift Voucher bearer can reach out to Customer service desk at the Stores or Customer Care at Toll free number 18008910001/18001027382 or Email at customerservice@ril.com.",
            "16.For any Reliance Retail GV queries / issues related to receiving of the voucher, please reach out to customer care via gvhelpdesk.com or customer care toll free number 18001033314",
            "17.The Gift Voucher is binding for all applicable laws of India.",
            "18.All disputes are subject to the jurisdiction of courts at Mumbai only."
        ],
        "redeem_steps": [
            "Visit listed outlet. You can locate the outlet on <a href='storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a>",
            "Select your choice of product",
            "Share the voucher code with the cashier before billing. You can make the balance payment by any other payment mode"
        ],
        "instructions": [
            "<ul>",
            "<li>Gift Vouchers CAN be used to buy discounted products. </li>",
            "<li>Multiple Gift Vouchers CAN be used in one bill.</li>",
            "<li>Gift Vouchers CAN be used at all Listed Outlets on <a href='https://storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a></li>",
            "<li>Gift Vouchers CANNOT be used online</li>",
            "</ul>"
        ],
        "created_at": "2023-04-24T06:38:49.878Z",
        "updated_at": "2023-04-24T06:38:49.878Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "6e8cd230-58fd-4a10-a88c-9ee5397aa313",
            "brand_id": "443ec643-4b51-4c91-8973-20cd956907ad",
            "name": "Reliance Jewels Rs 5000",
            "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "443ec643-4b51-4c91-8973-20cd956907ad",
                "name": "Reliance Jewels",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg",
                "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
                "created_at": "2023-04-24T06:28:19.190Z",
                "updated_at": "2023-05-20T06:13:55.315Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "16a3d30e-e928-4a91-b882-571fda36258e",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "ae902181-fb1a-4062-b378-8497198c0774",
        "vendor_product_ref": "JackJones4KViGCuoQefnSXaY",
        "cost_price": "2375.0",
        "vendor_discount_percent": "5.0",
        "product_price": "2500.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 10000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This Gift Voucher is issued by Reliance Retail Limited (Reliance).",
            "2.This Gift Voucher is redeemable, and it is valid only for a minimum period of 6 months from the date of receipt.",
            "3.Gift Voucher can be redeemed at Reliance SMART, Reliance Smart Point, Reliance Digital, Reliance Trends, Reliance Jewels and My Jio Stores in India.",
            "4.Gift Voucher can’t be exchanged for cash.",
            "5.This Gift Voucher is not valid on purchase of Gold/Silver Coins.",
            "6.This Gift Voucher can be redeemed only once. Any unused amount will lapse.",
            "7.No extension of the Validity period nor refund of the value of Gift Voucher in case of failure to use the Gift Voucher on or before the validity period.",
            "8.Reliance shall not be responsible for loss or misuse of Gift Voucher and no duplicate or compensation in lieu of the Gift Voucher shall be given by Reliance.",
            "9.Reliance overall liability will not exceed the value of the Gift Voucher.",
            "10.Bearer of the Gift Voucher shall be deemed to have read, understood and accepted these terms and conditions.",
            "11.Bearer of the code of Gift Voucher is deemed to be the beneficiary of this Gift Voucher. Any redemption by the bearer of Gift Voucher shall be considered as a valid discharge of liabilities by Reliance.",
            "12.Reliance shall not be liable under any circumstances towards any loss or damage or expenses or cost or any third-party liability, whether directly or indirectly arising out of or in relation to use of Gift Voucher and redemption thereunder by the bearer.",
            "13.Reliance reserves its right to modify/amend the terms and conditions of the Gift Voucher at any time without prior notice and such modifications shall be binding on the user/bearer of the Gift Voucher.",
            "14.Any dispute with regard to Product liability, guarantee, warranty and quality of the Products to be purchased under redemption of the Gift Voucher shall be addressed to the respective Manufacturer/ Brand Owner and Reliance shall not be held responsible/liable for the same. The guarantee and warranty of the Products shall be transferred, as received from the respective Manufacturer/Distributor.",
            "15.In case of any issue faced by the Gift Voucher bearer, the Gift Voucher bearer can reach out to Customer service desk at the Stores or Customer Care at Toll free number 18008910001/18001027382 or Email at customerservice@ril.com.",
            "16.For any Reliance Retail GV queries / issues related to receiving of the voucher, please reach out to customer care via gvhelpdesk.com or customer care toll free number 18001033314",
            "17.The Gift Voucher is binding for all applicable laws of India.",
            "18.All disputes are subject to the jurisdiction of courts at Mumbai only."
        ],
        "redeem_steps": [
            "Visit listed outlet. You can locate the outlet on <a href='storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a>",
            "Select your choice of product",
            "Share the voucher code with the cashier before billing. You can make the balance payment by any other payment mode"
        ],
        "instructions": [
            "<ul>",
            "<li>Gift Vouchers CAN be used to buy discounted products. </li>",
            "<li>Multiple Gift Vouchers CAN be used in one bill.</li>",
            "<li>Gift Vouchers CAN be used at all Listed Outlets on <a href='https://storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a></li>",
            "<li>Gift Vouchers CANNOT be used online</li>",
            "</ul>"
        ],
        "created_at": "2023-04-24T06:38:49.511Z",
        "updated_at": "2023-04-24T06:38:49.511Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "ae902181-fb1a-4062-b378-8497198c0774",
            "brand_id": "443ec643-4b51-4c91-8973-20cd956907ad",
            "name": "Reliance Jewels Rs 2500",
            "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "443ec643-4b51-4c91-8973-20cd956907ad",
                "name": "Reliance Jewels",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg",
                "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
                "created_at": "2023-04-24T06:28:19.190Z",
                "updated_at": "2023-05-20T06:13:55.315Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "b09deac4-0090-4dd6-8ea9-5baa0d635d9a",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "da4b7da6-9c55-4ac3-b774-443ff46e0e5b",
        "vendor_product_ref": "Cromal06iVDqb5Yv79W20",
        "cost_price": "1900.0",
        "vendor_discount_percent": "5.0",
        "product_price": "2000.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 8000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This Gift Voucher is issued by Reliance Retail Limited (Reliance).",
            "2.This Gift Voucher is redeemable, and it is valid only for a minimum period of 6 months from the date of receipt.",
            "3.Gift Voucher can be redeemed at Reliance SMART, Reliance Smart Point, Reliance Digital, Reliance Trends, Reliance Jewels and My Jio Stores in India.",
            "4.Gift Voucher can’t be exchanged for cash.",
            "5.This Gift Voucher is not valid on purchase of Gold/Silver Coins.",
            "6.This Gift Voucher can be redeemed only once. Any unused amount will lapse.",
            "7.No extension of the Validity period nor refund of the value of Gift Voucher in case of failure to use the Gift Voucher on or before the validity period.",
            "8.Reliance shall not be responsible for loss or misuse of Gift Voucher and no duplicate or compensation in lieu of the Gift Voucher shall be given by Reliance.",
            "9.Reliance overall liability will not exceed the value of the Gift Voucher.",
            "10.Bearer of the Gift Voucher shall be deemed to have read, understood and accepted these terms and conditions.",
            "11.Bearer of the code of Gift Voucher is deemed to be the beneficiary of this Gift Voucher. Any redemption by the bearer of Gift Voucher shall be considered as a valid discharge of liabilities by Reliance.",
            "12.Reliance shall not be liable under any circumstances towards any loss or damage or expenses or cost or any third-party liability, whether directly or indirectly arising out of or in relation to use of Gift Voucher and redemption thereunder by the bearer.",
            "13.Reliance reserves its right to modify/amend the terms and conditions of the Gift Voucher at any time without prior notice and such modifications shall be binding on the user/bearer of the Gift Voucher.",
            "14.Any dispute with regard to Product liability, guarantee, warranty and quality of the Products to be purchased under redemption of the Gift Voucher shall be addressed to the respective Manufacturer/ Brand Owner and Reliance shall not be held responsible/liable for the same. The guarantee and warranty of the Products shall be transferred, as received from the respective Manufacturer/Distributor.",
            "15.In case of any issue faced by the Gift Voucher bearer, the Gift Voucher bearer can reach out to Customer service desk at the Stores or Customer Care at Toll free number 18008910001/18001027382 or Email at customerservice@ril.com.",
            "16.For any Reliance Retail GV queries / issues related to receiving of the voucher, please reach out to customer care via gvhelpdesk.com or customer care toll free number 18001033314",
            "17.The Gift Voucher is binding for all applicable laws of India.",
            "18.All disputes are subject to the jurisdiction of courts at Mumbai only."
        ],
        "redeem_steps": [
            "Visit listed outlet. You can locate the outlet on <a href='storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a>",
            "Select your choice of product",
            "Share the voucher code with the cashier before billing. You can make the balance payment by any other payment mode"
        ],
        "instructions": [
            "<ul>",
            "<li>Gift Vouchers CAN be used to buy discounted products. </li>",
            "<li>Multiple Gift Vouchers CAN be used in one bill.</li>",
            "<li>Gift Vouchers CAN be used at all Listed Outlets on <a href='https://storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a></li>",
            "<li>Gift Vouchers CANNOT be used online</li>",
            "</ul>"
        ],
        "created_at": "2023-04-24T06:38:49.194Z",
        "updated_at": "2023-04-24T06:38:49.194Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "da4b7da6-9c55-4ac3-b774-443ff46e0e5b",
            "brand_id": "443ec643-4b51-4c91-8973-20cd956907ad",
            "name": "Reliance Jewels Rs 2000",
            "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "443ec643-4b51-4c91-8973-20cd956907ad",
                "name": "Reliance Jewels",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg",
                "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
                "created_at": "2023-04-24T06:28:19.190Z",
                "updated_at": "2023-05-20T06:13:55.315Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "539d6dde-902d-411d-b1b6-dadc0071bbc9",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "829e9937-5919-4c99-9a42-71377d8981f9",
        "vendor_product_ref": "Cromal06iVDqb5Yv79W20",
        "cost_price": "950.0",
        "vendor_discount_percent": "5.0",
        "product_price": "1000.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 4000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This Gift Voucher is issued by Reliance Retail Limited (Reliance).",
            "2.This Gift Voucher is redeemable, and it is valid only for a minimum period of 6 months from the date of receipt.",
            "3.Gift Voucher can be redeemed at Reliance SMART, Reliance Smart Point, Reliance Digital, Reliance Trends, Reliance Jewels and My Jio Stores in India.",
            "4.Gift Voucher can’t be exchanged for cash.",
            "5.This Gift Voucher is not valid on purchase of Gold/Silver Coins.",
            "6.This Gift Voucher can be redeemed only once. Any unused amount will lapse.",
            "7.No extension of the Validity period nor refund of the value of Gift Voucher in case of failure to use the Gift Voucher on or before the validity period.",
            "8.Reliance shall not be responsible for loss or misuse of Gift Voucher and no duplicate or compensation in lieu of the Gift Voucher shall be given by Reliance.",
            "9.Reliance overall liability will not exceed the value of the Gift Voucher.",
            "10.Bearer of the Gift Voucher shall be deemed to have read, understood and accepted these terms and conditions.",
            "11.Bearer of the code of Gift Voucher is deemed to be the beneficiary of this Gift Voucher. Any redemption by the bearer of Gift Voucher shall be considered as a valid discharge of liabilities by Reliance.",
            "12.Reliance shall not be liable under any circumstances towards any loss or damage or expenses or cost or any third-party liability, whether directly or indirectly arising out of or in relation to use of Gift Voucher and redemption thereunder by the bearer.",
            "13.Reliance reserves its right to modify/amend the terms and conditions of the Gift Voucher at any time without prior notice and such modifications shall be binding on the user/bearer of the Gift Voucher.",
            "14.Any dispute with regard to Product liability, guarantee, warranty and quality of the Products to be purchased under redemption of the Gift Voucher shall be addressed to the respective Manufacturer/ Brand Owner and Reliance shall not be held responsible/liable for the same. The guarantee and warranty of the Products shall be transferred, as received from the respective Manufacturer/Distributor.",
            "15.In case of any issue faced by the Gift Voucher bearer, the Gift Voucher bearer can reach out to Customer service desk at the Stores or Customer Care at Toll free number 18008910001/18001027382 or Email at customerservice@ril.com.",
            "16.For any Reliance Retail GV queries / issues related to receiving of the voucher, please reach out to customer care via gvhelpdesk.com or customer care toll free number 18001033314",
            "17.The Gift Voucher is binding for all applicable laws of India.",
            "18.All disputes are subject to the jurisdiction of courts at Mumbai only."
        ],
        "redeem_steps": [
            "Visit listed outlet. You can locate the outlet on <a href='storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a>",
            "Select your choice of product",
            "Share the voucher code with the cashier before billing. You can make the balance payment by any other payment mode"
        ],
        "instructions": [
            "<ul>",
            "<li>Gift Vouchers CAN be used to buy discounted products. </li>",
            "<li>Multiple Gift Vouchers CAN be used in one bill.</li>",
            "<li>Gift Vouchers CAN be used at all Listed Outlets on <a href='https://storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a></li>",
            "<li>Gift Vouchers CANNOT be used online</li>",
            "</ul>"
        ],
        "created_at": "2023-04-24T06:38:48.473Z",
        "updated_at": "2023-04-24T06:38:48.473Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "829e9937-5919-4c99-9a42-71377d8981f9",
            "brand_id": "443ec643-4b51-4c91-8973-20cd956907ad",
            "name": "Reliance Jewels Rs 1000",
            "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "443ec643-4b51-4c91-8973-20cd956907ad",
                "name": "Reliance Jewels",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg",
                "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
                "created_at": "2023-04-24T06:28:19.190Z",
                "updated_at": "2023-05-20T06:13:55.315Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "1fb3f966-c167-466c-9ab4-31e0c65458ec",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "6477cff3-0310-4ef7-8c5e-dca318435dd5",
        "vendor_product_ref": "Bata4xfRrUnT46Uv4iol",
        "cost_price": "475.0",
        "vendor_discount_percent": "5.0",
        "product_price": "500.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 2000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This Gift Voucher is issued by Reliance Retail Limited (Reliance).",
            "2.This Gift Voucher is redeemable, and it is valid only for a minimum period of 6 months from the date of receipt.",
            "3.Gift Voucher can be redeemed at Reliance SMART, Reliance Smart Point, Reliance Digital, Reliance Trends, Reliance Jewels and My Jio Stores in India.",
            "4.Gift Voucher can’t be exchanged for cash.",
            "5.This Gift Voucher is not valid on purchase of Gold/Silver Coins.",
            "6.This Gift Voucher can be redeemed only once. Any unused amount will lapse.",
            "7.No extension of the Validity period nor refund of the value of Gift Voucher in case of failure to use the Gift Voucher on or before the validity period.",
            "8.Reliance shall not be responsible for loss or misuse of Gift Voucher and no duplicate or compensation in lieu of the Gift Voucher shall be given by Reliance.",
            "9.Reliance overall liability will not exceed the value of the Gift Voucher.",
            "10.Bearer of the Gift Voucher shall be deemed to have read, understood and accepted these terms and conditions.",
            "11.Bearer of the code of Gift Voucher is deemed to be the beneficiary of this Gift Voucher. Any redemption by the bearer of Gift Voucher shall be considered as a valid discharge of liabilities by Reliance.",
            "12.Reliance shall not be liable under any circumstances towards any loss or damage or expenses or cost or any third-party liability, whether directly or indirectly arising out of or in relation to use of Gift Voucher and redemption thereunder by the bearer.",
            "13.Reliance reserves its right to modify/amend the terms and conditions of the Gift Voucher at any time without prior notice and such modifications shall be binding on the user/bearer of the Gift Voucher.",
            "14.Any dispute with regard to Product liability, guarantee, warranty and quality of the Products to be purchased under redemption of the Gift Voucher shall be addressed to the respective Manufacturer/ Brand Owner and Reliance shall not be held responsible/liable for the same. The guarantee and warranty of the Products shall be transferred, as received from the respective Manufacturer/Distributor.",
            "15.In case of any issue faced by the Gift Voucher bearer, the Gift Voucher bearer can reach out to Customer service desk at the Stores or Customer Care at Toll free number 18008910001/18001027382 or Email at customerservice@ril.com.",
            "16.For any Reliance Retail GV queries / issues related to receiving of the voucher, please reach out to customer care via gvhelpdesk.com or customer care toll free number 18001033314",
            "17.The Gift Voucher is binding for all applicable laws of India.",
            "18.All disputes are subject to the jurisdiction of courts at Mumbai only."
        ],
        "redeem_steps": [
            "Visit listed outlet. You can locate the outlet on <a href='storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a>",
            "Select your choice of product",
            "Share the voucher code with the cashier before billing. You can make the balance payment by any other payment mode"
        ],
        "instructions": [
            "<ul>",
            "<li>Gift Vouchers CAN be used to buy discounted products. </li>",
            "<li>Multiple Gift Vouchers CAN be used in one bill.</li>",
            "<li>Gift Vouchers CAN be used at all Listed Outlets on <a href='https://storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a></li>",
            "<li>Gift Vouchers CANNOT be used online</li>",
            "</ul>"
        ],
        "created_at": "2023-04-24T06:38:48.144Z",
        "updated_at": "2023-04-24T06:38:48.144Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "6477cff3-0310-4ef7-8c5e-dca318435dd5",
            "brand_id": "443ec643-4b51-4c91-8973-20cd956907ad",
            "name": "Reliance Jewels Rs 500",
            "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "443ec643-4b51-4c91-8973-20cd956907ad",
                "name": "Reliance Jewels",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg",
                "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
                "created_at": "2023-04-24T06:28:19.190Z",
                "updated_at": "2023-05-20T06:13:55.315Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "c418ab29-0a42-4633-927e-e6d849aff791",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "8dcfd551-89dc-41cf-b106-52167da5935e",
        "vendor_product_ref": "RelianceJewelsKVJwTEjYH0ESLO18",
        "cost_price": "237.5",
        "vendor_discount_percent": "5.0",
        "product_price": "250.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 1000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This Gift Voucher is issued by Reliance Retail Limited (Reliance).",
            "2.This Gift Voucher is redeemable, and it is valid only for a minimum period of 6 months from the date of receipt.",
            "3.Gift Voucher can be redeemed at Reliance SMART, Reliance Smart Point, Reliance Digital, Reliance Trends, Reliance Jewels and My Jio Stores in India.",
            "4.Gift Voucher can’t be exchanged for cash.",
            "5.This Gift Voucher is not valid on purchase of Gold/Silver Coins.",
            "6.This Gift Voucher can be redeemed only once. Any unused amount will lapse.",
            "7.No extension of the Validity period nor refund of the value of Gift Voucher in case of failure to use the Gift Voucher on or before the validity period.",
            "8.Reliance shall not be responsible for loss or misuse of Gift Voucher and no duplicate or compensation in lieu of the Gift Voucher shall be given by Reliance.",
            "9.Reliance overall liability will not exceed the value of the Gift Voucher.",
            "10.Bearer of the Gift Voucher shall be deemed to have read, understood and accepted these terms and conditions.",
            "11.Bearer of the code of Gift Voucher is deemed to be the beneficiary of this Gift Voucher. Any redemption by the bearer of Gift Voucher shall be considered as a valid discharge of liabilities by Reliance.",
            "12.Reliance shall not be liable under any circumstances towards any loss or damage or expenses or cost or any third-party liability, whether directly or indirectly arising out of or in relation to use of Gift Voucher and redemption thereunder by the bearer.",
            "13.Reliance reserves its right to modify/amend the terms and conditions of the Gift Voucher at any time without prior notice and such modifications shall be binding on the user/bearer of the Gift Voucher.",
            "14.Any dispute with regard to Product liability, guarantee, warranty and quality of the Products to be purchased under redemption of the Gift Voucher shall be addressed to the respective Manufacturer/ Brand Owner and Reliance shall not be held responsible/liable for the same. The guarantee and warranty of the Products shall be transferred, as received from the respective Manufacturer/Distributor.",
            "15.In case of any issue faced by the Gift Voucher bearer, the Gift Voucher bearer can reach out to Customer service desk at the Stores or Customer Care at Toll free number 18008910001/18001027382 or Email at customerservice@ril.com.",
            "16.For any Reliance Retail GV queries / issues related to receiving of the voucher, please reach out to customer care via gvhelpdesk.com or customer care toll free number 18001033314",
            "17.The Gift Voucher is binding for all applicable laws of India.",
            "18.All disputes are subject to the jurisdiction of courts at Mumbai only."
        ],
        "redeem_steps": [
            "Visit listed outlet. You can locate the outlet on <a href='storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a>",
            "Select your choice of product",
            "Share the voucher code with the cashier before billing. You can make the balance payment by any other payment mode"
        ],
        "instructions": [
            "<ul>",
            "<li>Gift Vouchers CAN be used to buy discounted products. </li>",
            "<li>Multiple Gift Vouchers CAN be used in one bill.</li>",
            "<li>Gift Vouchers CAN be used at all Listed Outlets on <a href='https://storelocator.ril.com/Retail.aspx'>storelocator.ril.com/Retail.aspx</a></li>",
            "<li>Gift Vouchers CANNOT be used online</li>",
            "</ul>"
        ],
        "created_at": "2023-04-24T06:38:47.615Z",
        "updated_at": "2023-04-24T06:38:47.615Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "8dcfd551-89dc-41cf-b106-52167da5935e",
            "brand_id": "443ec643-4b51-4c91-8973-20cd956907ad",
            "name": "Reliance Jewels Rs 250",
            "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "443ec643-4b51-4c91-8973-20cd956907ad",
                "name": "Reliance Jewels",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1663236795361_ktg41g3l82w8std.jpeg",
                "description": "Find the widest collections of gold and diamond jewellery at Reliance Jewels. This chain of premium jewellery showrooms brings you the most exquisite and royal designs. Visit for a memorable shopping experience and get assured value for money. Redeem your vouchers seamlessly on your next purchases.",
                "created_at": "2023-04-24T06:28:19.190Z",
                "updated_at": "2023-05-20T06:13:55.315Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "c43eeb5d-23db-4c45-94d0-d12183b2d9b1",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "71a124e4-0a3e-47ac-ba85-a9aa9f602db4",
        "vendor_product_ref": "JackJones4KViGCuoQefnSXaY",
        "cost_price": "2350.0",
        "vendor_discount_percent": "6.0",
        "product_price": "2500.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 10000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This is Ketan Diamonds Insta Gift Voucher (GV) / Gift Card (GC) and would only be accepted at Ketan Diamonds website i.e. https://www.ketandiamonds.com and not on any other products/services.",
            "2.The person who has the Ketan Diamonds GV / GC Code is deemed to be the beneficiary.",
            "3.Ketan Diamonds is not responsible if the Gift card is lost, stolen or used without permission.",
            "4.More than One GV / GC can be used in one bill/transaction.",
            "5.This is a One-time use GV / GC with an expiration date.",
            "6.No credit note / refund for the unused balance amount of the GV / GC will be given.",
            "7.Any such unused balance amount shall stand lapsed automatically.",
            "8.Ketan Diamonds GV / GC CANNOT be revalidated once expired or cancelled under any situations",
            "9.Ketan Diamonds GV / GC can be clubbed with on-going promotions & offers.",
            "10.Ketan Diamonds GV / GC cannot be redeemed on specific block out dates. Ketan Diamonds may add or delete any date(s)/period(s) on its sole discretion without any liability.",
            "11.Any dispute related to the GV / GC should be referred to the issuing company and the decision of the issuing company shall be final. In case of any legal disputes, the courts at Mumbai shall have the exclusive jurisdiction.",
            "12.Ketan Diamonds shall on best effort basis attempt to accept Insta Gift Vouchers (GV) / Gift Card (GC), but on account of any technical reason or for any reason beyond control of Ketan Diamonds, GV / GC may not get accepted and Ketan Diamonds shall have no liability for the same.",
            "13.If an Insta Gift Voucher (GV) /Gift Card (GC) gets blocked on account of technical issue, it would get enabled in 72 hours. In case of transaction failures after Insta Gift Voucher (GV) / Gift Card (GC) is applied, amount would be automatically refunded to the same cards within 48 hours.",
            "14.For any queries / issues related to GV / GC, you can write in to bit.ly/2CsY6BX or call 1800 1033 314.",
            "15.Ketan Diamonds reserves the rights to edit/change the terms and conditions for the Insta Gift Voucher (GV) / Gift Card (GC) at any time without any notice or liability.",
            "16.Ketan Diamonds has the final authority on the interpretation of these rules.",
            "17.Ketan Diamonds Gold Coin Insta Gift Voucher (GV) / Gift Card can only be used to purchase Gold Coins.",
            "18.Ketan Diamonds Gold Jewellery Insta Gift Voucher (GV) / Gift Card can only be used to purchase Gold Jewellery.",
            "19.Ketan Diamonds Diamond Jewellery Insta Gift Voucher (GV) / Gift Card can only be used to purchase Diamond Jewellery.",
            "20.Ketan Diamonds reserves the right to withdraw Insta Gift Voucher (GV) / Gift Card (GC) scheme/offer before the completion of validity period without any notice or liability at its sole discretion.",
            "21.Ketan Diamonds reserves the right to deny accepting any Insta Gift Voucher (GV) / Gift Card (GC), if it suspects that there is duplicity of cards.",
            "22.In no event the liability of Ketan Diamonds for any claims shall exceed the value of the Insta Gift Voucher (GV) / Gift Card (GC) in dispute."
        ],
        "redeem_steps": [
            "Visit www.ketandiamonds.com, select the product of your choice & add to cart.",
            "",
            "Click on Pay Online.",
            "",
            "Enter the voucher number in âVoucher Numberâ tab and click on âApplyâ button to redeem the same.",
            "",
            "Click on Proceed to checkout."
        ],
        "instructions": [
            "Multiple Gift Vouchers CAN be used in one transaction.",
            "Gift Vouchers are only ACCEPTED online at www.ketandiamonds.com",
            "Gift Vouchers CAN be clubbed with offers/promotions available online."
        ],
        "created_at": "2023-04-24T06:37:47.015Z",
        "updated_at": "2023-04-24T06:37:47.015Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "71a124e4-0a3e-47ac-ba85-a9aa9f602db4",
            "brand_id": "89de8e86-74dc-4f76-9288-5beb89612085",
            "name": "Ketan Diamonds Diamond Only Rs 2500",
            "description": "Ketan Diamonds Diamond Jewellery believes that each and every jewellery piece should be pure, perfect and precious. Browse through their collection, and come across the ones that are perfect for you. Pick Ketan Diamonds Diamond Jewellery Gift Cards and Gift Vouchers for a breezy, cashless shopping.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1617628231794_1ao771kldkn4m2zxu.png"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "89de8e86-74dc-4f76-9288-5beb89612085",
                "name": "Ketan Diamonds Diamond Only",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1617628231794_1ao771kldkn4m2zxu.png",
                "description": "Ketan Diamonds Diamond Jewellery believes that each and every jewellery piece should be pure, perfect and precious. Browse through their collection, and come across the ones that are perfect for you. Pick Ketan Diamonds Diamond Jewellery Gift Cards and Gift Vouchers for a breezy, cashless shopping.",
                "created_at": "2023-04-24T06:28:14.386Z",
                "updated_at": "2023-05-20T06:13:59.570Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "0e2aaf07-522a-4525-a80d-d18914e2cbd0",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "ab36ba17-ddbd-4cce-ba0f-2c2a68dd7ad7",
        "vendor_product_ref": "BenettonRwJ6cqVWqPPMLlBH",
        "cost_price": "4975.0",
        "vendor_discount_percent": "0.5",
        "product_price": "5000.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 20000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This is a PC Jeweller Instant Gift Voucher / Card (GV) and would be accepted at listed outlets and can also be redeemed on PC Jeweller website i.e. www.pcjeweller.com",
            "2.The person who has the PC Jeweller GV Code is deemed to be the beneficiary.",
            "3.Do inform the cashier that you plan using the GV for making payments before billing.",
            "4.Only the listed PC Jeweller outlets at its sole discretion accept the GV. PC Jeweller may add or remove an outlet without giving any prior notice.",
            "5.More than one GV can be used in one bill.",
            "6.This is a ONE time use GV.",
            "7.No Credit note / Refund for the unused amount of the GV will be given.",
            "8.In case of Product Returns, no refund by way of cash will be given for amount paid through GV.",
            "9.PC Jeweller Insta Gift Voucher (GV) / Gift Card CANNOT be revalidated once expired.",
            "10.PC Jeweller Insta Gift Voucher (GV) / Gift Card can be used during sale.",
            "11.Any dispute related to the Insta Gift Voucher (GV) should be referred to the issuing company and the decision of the issuing company shall be final.",
            "12.PC Jeweller Gold Coin Insta Gift Voucher (GV) / Gift Card can only be used to purchase Gold Coins.",
            "13.PC Jeweller Gold Jewellery Insta Gift Voucher (GV) / Gift Card can only be used to purchase Gold Jewellery.",
            "14.PC Jeweller Diamond Jewellery Insta Gift Voucher (GV) / Gift Card can only be used to purchase Diamond Jewellery.",
            "15.PC Jeweller makes full efforts to accept Instant Gift Voucher (GV) / Gift Card, but on account of any technical / administrative reasons an outlet may refuse to accept the same.",
            "16.If an Instant Gift Voucher (GV) / Gift Card get blocked on account of technical issue, it would get enabled in 72 hours.",
            "17.Please contact PC Jeweller Showroom manager for any acceptance issue and if issue is still not resolved, you can write in to bit.ly/2CsY6BX or call 18001033314 for immediate help."
        ],
        "redeem_steps": [
            "Use the outlet locator to locate the nearest outlet that accepts this Gift Voucher.Select your choice of product.Share your Gift Voucher with the cashier at the time of billing & pay the remaining amount by cash or card if required."
        ],
        "instructions": [
            "<ul>",
            "<li>Gift voucher can be used at listed PC Jeweller outlets and on PC Jeweller website i.e. < ahref='https://www.pcjeweller.com/'>www.pcjeweller.com</a></li>",
            "<li>Multiple Gift voucher can be used in one bill.</li>",
            "<li>Gift voucher can be clubbed with on-going promotions/offers.</li>",
            "</ul>"
        ],
        "created_at": "2023-04-24T06:38:31.208Z",
        "updated_at": "2023-04-24T06:38:31.208Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "ab36ba17-ddbd-4cce-ba0f-2c2a68dd7ad7",
            "brand_id": "5c1aa8f2-e4a2-4427-804e-ccf694dc184b",
            "name": "PC Jeweller Gold Coin Rs 5000",
            "description": "Get authentic gold coins with 24kt purity from PC Jeweller. The available sizes include 1 gm, 2 gm, 5 gm, 10 gm, and 20 gm. Choose from interesting designs like floral designs and religious figures. PC Jeweller gold coin Gift Cards available at the best prices from GyFTR. You can instantly redeem your Gift Card on your gold coin purchase.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1593582282739_mp92eskc2xquwj.png"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "5c1aa8f2-e4a2-4427-804e-ccf694dc184b",
                "name": "PC Jeweller Gold Coin",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1593582282739_mp92eskc2xquwj.png",
                "description": "Get authentic gold coins with 24kt purity from PC Jeweller. The available sizes include 1 gm, 2 gm, 5 gm, 10 gm, and 20 gm. Choose from interesting designs like floral designs and religious figures. PC Jeweller gold coin Gift Cards available at the best prices from GyFTR. You can instantly redeem your Gift Card on your gold coin purchase.",
                "created_at": "2023-04-24T06:28:17.587Z",
                "updated_at": "2023-05-20T06:13:57.622Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    },
    {
        "id": "15c652bf-ac1f-44c8-b91c-e890f4ce6205",
        "vendor_id": "12b3ef33-2299-4932-a4de-33a35cf32c86",
        "product_code_id": "43f667c4-5b23-403f-bf36-ebdb5968e8bd",
        "vendor_product_ref": "Cromal06iVDqb5Yv79W20",
        "cost_price": "1940.0",
        "vendor_discount_percent": "3.0",
        "product_price": "2000.0",
        "currency": "INR",
        "margin_percent": "0.0",
        "cogopoint_factor": "4.0",
        "cogopoints": 8000,
        "available_stock": -1,
        "purchase_limit": -1,
        "is_stock_available": true,
        "is_first_priority": true,
        "tags": [],
        "ranking": 1,
        "validity_start": null,
        "validity_end": null,
        "status": "active",
        "platform": null,
        "tnc": [
            "1.This is a A.himanshu Insta Gift Voucher (GV) / Gift Card (GC) and would be accepted online at https://euphoriajewellery.in/ and can be used to purchase Gold coins Only.",
            "2.The person who has the A.himanshu GV / GC Code is deemed to be the beneficiary.",
            "3.More than one GV / GC can be used in one bill.",
            "4.This is a ONE time use GV / GC.",
            "5.No Credit note / Refund for the unused amount of the GV / GC will be given.",
            "6.A.himanshu GV / GC CANNOT be revalidated once expired.",
            "7.A.himanshu GV / GC can be clubbed with any on-going promotions on the website. However the Insta GV / GC cannot be clubbed with any other coupon/s.",
            "8.A.himanshu GV / GC cannot be redeemed on specific block out dates. A.himanshu may add or delete any date on its sole discretion.",
            "9.Any dispute related to the GV / GC should be referred to the issuing company and the decision of the issuing company shall be final.",
            "10.If an Insta Gift Voucher (GV) /Gift Card (GC) gets blocked on account of technical issue, it would get enabled in 72 hours.",
            "11.For any queries / issues related to GV / GC, raise a request at www.gvhelpdesk.com"
        ],
        "redeem_steps": [
            "Visit : <span><a target=\"_blank\" href=\"https://euphoriajewellery.in//\">https://euphoriajewellery.in//</a></span>Select your <span>product </span> & add to cart Enter : Gift Voucher Code & click on Redeem Now. -Enter coupon code manually and click on Apply GyFTR Coupon"
        ],
        "instructions": [
            "<ul>? ? ? ?? <li>Multiple Gift Vouchers can be used in 1 bill <li> Gift Vouchers can be clubbed with on-going promotions? <li>Gift Vouchers can Only be used online on https://euphoriajewellery.in/ <li class=\"no\">Gift Vouchers cannot be clubbed with other coupon(s)? </ul>"
        ],
        "created_at": "2023-04-24T06:38:51.334Z",
        "updated_at": "2023-04-24T06:38:51.334Z",
        "sku_id": null,
        "vendor": {},
        "product_code": {
            "id": "43f667c4-5b23-403f-bf36-ebdb5968e8bd",
            "brand_id": "a402987e-c18f-4b93-939c-37b87c24d35d",
            "name": "Euphoria Jewellery Gold Coin Rs 2000",
            "description": "Euphoria Jewellery began more than a decade ago as A.Himanshu & Co. Being miners of jewels, they took the next step of manufacturing them. Visit their official website and buy gold and silver coins risk-free. Choose Euphoria Jewellery gift cards and gift vouchers for a cashless shopping experience.",
            "logo_urls": [
                "https://cdn.gyftr.com/comm_engine/prod/images/brands/1623052206676_1ohc63ujkpmbdlqs.jpeg"
            ],
            "code": null,
            "product_type": "VOUCHER",
            "brand": {
                "id": "a402987e-c18f-4b93-939c-37b87c24d35d",
                "name": "Euphoria Jewellery Gold Coin",
                "status": "active",
                "logo_url": "https://cdn.gyftr.com/comm_engine/prod/images/brands/1623052206676_1ohc63ujkpmbdlqs.jpeg",
                "description": "Euphoria Jewellery began more than a decade ago as A.Himanshu & Co. Being miners of jewels, they took the next step of manufacturing them. Visit their official website and buy gold and silver coins risk-free. Choose Euphoria Jewellery gift cards and gift vouchers for a cashless shopping experience.",
                "created_at": "2023-04-24T06:28:19.396Z",
                "updated_at": "2023-05-20T06:14:02.051Z"
            },
            "category": {
                "id": "1829a542-ceda-4567-930a-ca9d6b3c02e6",
                "category": "jewellery",
                "display_name": "Jewellery",
                "logo_url": "https://cogoport-production.sgp1.digitaloceanspaces.com/3ffa59b89ec6399fc8737bf524e3af6b/Jewellary.jpg",
                "status": "active"
            }
        },
        "product_attribute": null
    }
]